services:
  - type: web
    name: fastapi-demo
    env: python
    buildCommand: "pip install -r app/requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10127"
    plan: free